version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'zoomcamp-de-452200') }}"
    #database: zoomcamp-de-452200
    schema: "{{ env_var('DBT_SCHEMA', 'bike_data') }}"
    #schema: trips_data_all zoomcamp-de-452200.bike_data.
      # loaded_at_field: record_loaded_at
    tables:
      - name: baywheels_tripdata